version: "3"

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=airsonicdb
      - POSTGRES_USER=airsonic
      - POSTGRES_PASSWORD=passwd
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: on-failure

  airsonic:
    depends_on:
      - postgres
    image: ghcr.io/kagemomiji/airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/airsonicdb?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=airsonic
      - SPRING_DATASOURCE_PASSWORD=passwd
      # - CONTEXT_PATH= #optional
      # - JAVA_OPTS= #optional
    volumes:
      - ./data/airsonic:/var/airsonic
      - ./data/music:/var/music
      - ./data/playlists:/var/playlists
      - ./data/podcasts:/var/podcasts
    ports:
      - 4040:4040 # HTTP
      # - 1900:1900 # DLNA/UPnP
    # devices:
    #   - /dev/snd:/dev/snd #optional
    restart: on-failure
    